services:
  redis-primary:
    image: bitnami/redis:7.4
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    secrets:
      - redis_password
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - redis_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "$$(cat /run/secrets/redis_password)",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-secondary:
    image: bitnami/redis:7.4
    ports:
      - "6380:6379"
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD_FILE=/run/secrets/redis_password
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    secrets:
      - redis_password
    networks:
      - redis_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "$$(cat /run/secrets/redis_password)",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: devpiush/py_system_monitoring_app:latest
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=redis-primary
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password
    depends_on:
      - redis-primary
      - redis-secondary
    networks:
      - redis_network
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "sh",
    #       "-c",
    #       "curl -f http://localhost:5001/health || exit 1",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      mode: replicated
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  redis_password:
    external: true

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
    driver_opts:
      encrypted: "true"
