---
- name: Create ansible user
  user:
    name: ansible
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present
    create_home: yes

- name: Allow ansible user to sudo without password
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: "visudo -cf %s"

- name: Create .ssh directory for ansible user
  file:
    path: /home/ansible/.ssh
    state: directory
    mode: 0700
    owner: ansible
    group: ansible

- name: Copy authorized keys for ansible user
  copy:
    src: ../files/authorized_keys
    dest: /home/ansible/.ssh/authorized_keys
    mode: 0600
    owner: ansible
    group: ansible
