---
- name: Setup requirements on all nodes
  hosts: swarm
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Include user setup tasks
      include_tasks: tasks/user-setup.yaml

    - name: Include Docker setup tasks
      include_tasks: tasks/docker-setup.yaml

- name: Configure Docker Swarm
  hosts: swarm
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include Swarm setup tasks
      include_tasks: tasks/swarm-setup.yaml

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

- name: Configure Nginx reverse proxy
  hosts: managers
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include Nginx setup tasks
      include_tasks: tasks/nginx-setup.yaml

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
