name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup venv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python app.py &
          sleep 10
          curl --fail http://localhost:5001/health

  build:
    runs-on: ubuntu-latest
    needs: ["test"]

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag py_system_monitoring_app:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Tag the image with both the commit SHA and latest
        run: |
          docker tag py_system_monitoring_app:${{ github.sha }} ${{ vars.DOCKER_HUB_USERNAME }}/py_system_monitoring_app:latest

      - name: Push the image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_HUB_USERNAME }}/py_system_monitoring_app:${{ github.sha }}
          docker push ${{ vars.DOCKER_HUB_USERNAME }}/py_system_monitoring_app:latest
